import React, { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import { Brain, TrendingUp, AlertTriangle, Link2, Loader2 } from 'lucide-react';
import { wellApi } from '../services/api';
import FluidIndicatorsCard from './FluidIndicatorsCard';
import QualityWarnings from './QualityWarnings';
import ZoneSummary from './ZoneSummary';

const AIInterpretation = ({ wellId, curves, depthRange, data, onInterpretationComplete }) => {
  const [interpretation, setInterpretation] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    loadInterpretation();
  }, [wellId, curves, depthRange]);

  const loadInterpretation = async () => {
    setIsLoading(true);
    setError(null);

    try {
      const response = await wellApi.interpretWell(
        wellId,
        curves,
        depthRange.start,
        depthRange.stop
      );

      if (response.success) {
        setInterpretation(response.data);
        if (onInterpretationComplete) {
          onInterpretationComplete(response.data);
        }
      }
    } catch (err) {
      setError(err.response?.data?.error?.message || 'Failed to generate interpretation');
      console.error('Interpretation error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  if (isLoading) {
    return (
      <div className="card">
        <div className="flex items-center justify-center py-12">
          <Loader2 className="w-8 h-8 animate-spin text-primary-600" />
          <span className="ml-3 text-lg">Analyzing well data with AI...</span>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="card bg-red-50 border border-red-200">
        <p className="text-red-700">{error}</p>
        <button onClick={loadInterpretation} className="btn-primary mt-4">
          Retry
        </button>
      </div>
    );
  }

  if (!interpretation) {
    return null;
  }

  return (
    <div className="space-y-6">
      {/* NEW: Fluid Indicators - Show first for maximum impact! */}
      {interpretation.fluidIndicators && (
        <FluidIndicatorsCard fluidIndicators={interpretation.fluidIndicators} />
      )}

      {/* NEW: Quality Warnings */}
      {interpretation.qualityIssues && (
        <QualityWarnings qualityIssues={interpretation.qualityIssues} />
      )}

      {/* NEW: Zone Segmentation */}
      {interpretation.zones && (
        <ZoneSummary zones={interpretation.zones} />
      )}

      {/* Main Interpretation */}
      <div className="card">
        <div className="flex items-center mb-4">
          <Brain className="w-6 h-6 text-primary-600 mr-2" />
          <h3 className="text-xl font-semibold">AI Interpretation</h3>
        </div>

        <div className="prose max-w-none text-gray-700 leading-relaxed">
          <ReactMarkdown
            components={{
              h1: ({ node, ...props }) => <h1 className="text-2xl font-bold text-gray-900 mt-6 mb-4 pb-2 border-b border-gray-200" {...props} />,
              h2: ({ node, ...props }) => <h2 className="text-xl font-semibold text-primary-800 mt-6 mb-3 flex items-center" {...props} />,
              h3: ({ node, ...props }) => <h3 className="text-lg font-medium text-gray-800 mt-4 mb-2" {...props} />,
              p: ({ node, ...props }) => <p className="mb-4 text-gray-700 leading-relaxed" {...props} />,
              ul: ({ node, ...props }) => <ul className="list-disc pl-5 mb-4 space-y-1" {...props} />,
              ol: ({ node, ...props }) => <ol className="list-decimal pl-5 mb-4 space-y-1" {...props} />,
              li: ({ node, ...props }) => <li className="text-gray-700" {...props} />,
              strong: ({ node, ...props }) => <strong className="font-semibold text-gray-900" {...props} />,
              blockquote: ({ node, ...props }) => <blockquote className="border-l-4 border-primary-200 pl-4 italic text-gray-600 my-4" {...props} />,
            }}
          >
            {interpretation.interpretation}
          </ReactMarkdown>
        </div>

        <div className="mt-4 pt-4 border-t text-sm text-gray-500">
          Generated by {interpretation.metadata?.model || 'Claude AI'} on{' '}
          {new Date(interpretation.metadata?.timestamp).toLocaleString()}
        </div>
      </div>

      {/* Statistics */}
      <div className="card">
        <div className="flex items-center mb-4">
          <TrendingUp className="w-6 h-6 text-primary-600 mr-2" />
          <h3 className="text-xl font-semibold">Statistical Summary</h3>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          {Object.entries(interpretation.statistics || {}).map(([curve, stats]) => {
            if (!stats) return null;

            return (
              <div key={curve} className="bg-gray-50 p-4 rounded-lg">
                <h4 className="font-semibold text-primary-700 mb-2">{curve}</h4>
                <div className="space-y-1 text-sm">
                  <div className="flex justify-between">
                    <span className="text-gray-600">Min:</span>
                    <span className="font-medium">{stats.min.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Max:</span>
                    <span className="font-medium">{stats.max.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Mean:</span>
                    <span className="font-medium">{stats.mean.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Std Dev:</span>
                    <span className="font-medium">{stats.stdDev.toFixed(2)}</span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Anomalies */}
      {interpretation.anomalies && interpretation.anomalies.length > 0 && (
        <div className="card">
          <div className="flex items-center mb-4">
            <AlertTriangle className="w-6 h-6 text-yellow-600 mr-2" />
            <h3 className="text-xl font-semibold">Detected Anomalies</h3>
          </div>

          <div className="space-y-2">
            {interpretation.anomalies.slice(0, 10).map((anomaly, index) => (
              <div
                key={index}
                className="flex items-center justify-between p-3 bg-yellow-50 border border-yellow-200 rounded-lg"
              >
                <div>
                  <span className="font-medium">{anomaly.curve}</span>
                  <span className="text-gray-600 mx-2">at</span>
                  <span className="font-medium">{anomaly.depth.toFixed(1)} ft</span>
                </div>
                <div className="text-right">
                  <div className="text-sm text-gray-600">Value: {anomaly.value.toFixed(2)}</div>
                  <div className="text-xs text-yellow-700">
                    {anomaly.deviation.toFixed(1)}σ deviation
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Correlations */}
      {interpretation.correlations && interpretation.correlations.length > 0 && (
        <div className="card">
          <div className="flex items-center mb-4">
            <Link2 className="w-6 h-6 text-primary-600 mr-2" />
            <h3 className="text-xl font-semibold">Curve Correlations</h3>
          </div>

          <div className="space-y-2">
            {interpretation.correlations.slice(0, 10).map((corr, index) => (
              <div
                key={index}
                className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"
              >
                <div>
                  <span className="font-medium">{corr.curve1}</span>
                  <span className="text-gray-600 mx-2">↔</span>
                  <span className="font-medium">{corr.curve2}</span>
                </div>
                <div className="flex items-center">
                  <div className="w-32 bg-gray-200 rounded-full h-2 mr-3">
                    <div
                      className={`h-2 rounded-full ${corr.correlation > 0 ? 'bg-green-500' : 'bg-red-500'
                        }`}
                      style={{ width: `${Math.abs(corr.correlation) * 100}%` }}
                    />
                  </div>
                  <span className="font-medium w-16 text-right">
                    {corr.correlation.toFixed(3)}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default AIInterpretation;